### ISSUE TITLE
Problem with 119 task (Brain Fibo)

### ISSUE THREAD

**Issue by reheda** [meyer1994/CodeAbbeySolutionDownloader#1]
Hi. I've tried ur solution and faced with problem.

That's due to of 119 Task. "0119 - Brainfuck - Brain Fibo.html" doesn't contain code of solution because it is challenge. Maybe better just skip this task and output message with the reason and continue working with other ones.

Error code:
```
Could not find the "code" tag in htmls\0119 - Brainfuck - Brain Fibo.html
0119 - Brain Fibo.bf (101 of 125)
Traceback (most recent call last):
  File "parser_script.py", line 72, in <module>
    f.write(code)
TypeError: write() argument must be str, not None
```

**Comment by meyer1994** [comment]
I've not solved, nor participated, in any challenge. I think. Could you post some HTML of the solution page for me to see? I think it would make it clearer for me to solve the issue.

**Comment by reheda** [comment]
Here you go.

[0119 - Brainfuck - Brain Fibo.zip](https://github.com/meyer1994/CodeAbbeySolutionDownloader/files/793033/0119.-.Brainfuck.-.Brain.Fibo.zip)

**Comment by meyer1994** [comment]
Interesting. I guess I will just surround the part of the code with a try block and make it print something telling the code could not be retrieved. Do you have any suggestions?

**Comment by reheda** [comment]
Unfortunately, i'm not familiar with python, but seems you shouldn't write **None** to file. 
So maybe change the **get_code** method:
`return None` to `return ''`


Btw, you should increment iterator by 1 to output correctly message with counter.
(I'm talking about line 81: `print(l + ' ({} of {})'.format(i, len(files)))`

For now the output looks like:
>0036 - Code Guesser.java (0 of 3)
0119 - Brain Fibo.bf (1 of 3)
0171 - Tree Height Measurement.java (2 of 3)

**Comment by meyer1994** [comment]
ca8d3550ff1c36b6d6f52fa39c6d61d16867c632
 Fixed the problem with the index. Now it shows:

> (1 of 3)
> (2 of 3)
> etc...

If there is no code tag, the script will output a message telling the user there is no `code` tag and will output another message telling that the file won't be created.
