### ISSUE TITLE
Addition to 'Requirements'

### ISSUE THREAD

**Issue by reheda** [meyer1994/CodeAbbeySolutionDownloader#2]
I've installed fresh python 3.6.0 and faced with issue.

Error message:
`bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?`

So maybe add lxml library to **Requirements** block and solution to get it ?
like `pip install lxml`

**Comment by meyer1994** [comment]
I will add it to the 'requirements' section of the README and add a requirements.txt to it. As soon as I can.

**Comment by meyer1994** [comment]
Added a requirements.txt file and updated the README.
Marking as solved.

**Comment by meyer1994** [comment]
@reheda 
Do you think this is a nice fix? Or should I try to make the script check for the libs before doing anything?

**Comment by meyer1994** [comment]
Commit 2f12853d638b07c0441b691736c1c4a781f389f6: added some try blocks to print some messages if libs not installed.
